# Generated by Django 3.1.7 on 2021-05-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('longitude', models.CharField(max_length=30, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=30, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('VKONTAKTE', 'Vkontakte')], max_length=9, verbose_name='Соц сеть')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contacts.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Соц сеть',
                'verbose_name_plural': 'Соц сети',
            },
        ),
    ]
